### ISSUE TITLE
Partly Items don't appear

### ISSUE THREAD

**Issue by doublenote1** [skuroda/FindKeyConflicts#6]
Dear Skuroda

I use Windows 7 64bit and have installed Sublime Text3 Dev latest version.
It seems that Partly I can't get proper result.
What I suppose that should appear doesn't.
I set every plugin custom 'Default (Windows).sublime-keymap" in plagin name folder in Packages Folder.
And the result in console when I excuted "All Key Maps to Buffer" is bellow.

Exception in thread Thread-34:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "find_key_conflicts in C:\Users\KIYO\AppData\Roaming\Sublime Text 3\Installed Packages\FindKeyConflicts.sublime-package", line 526, in run
  File "find_key_conflicts in C:\Users\KIYO\AppData\Roaming\Sublime Text 3\Installed Packages\FindKeyConflicts.sublime-package", line 453, in manage_package
  File "find_key_conflicts in C:\Users\KIYO\AppData\Roaming\Sublime Text 3\Installed Packages\FindKeyConflicts.sublime-package", line 531, in handle_key_map
TypeError: 'NoneType' object is not iterable

**Comment by skuroda** [comment]
Hi @doublenote1, apologize for the delay. I've been a bit busy lately but will try to get to this soon.
