### ISSUE TITLE
It does not work with Sublime Text2

### ISSUE THREAD

**Issue by kokosabu** [skuroda/FindKeyConflicts#9]
Sublime Text2 (Version 2.0.2, Build 2221) In, python version for 2.6.9, logger.hasHandlers can not be used. For this reason, it is no longer able to use FindKeyConflicts.

**Comment by kpym** [comment]
I confirm this too. 
```
Reloading plugin D:\MyPrograms\Sublime Text 2\Data\Packages\FindKeyConflicts\find_key_conflicts.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\find_key_conflicts.py", line 18, in <module>
    from lib.package_resources import *
  File ".\lib\package_resources.py", line 293, in <module>
    reload(sys.modules["find_key_conflicts"])
  File ".\find_key_conflicts.py", line 38, in <module>
    if not logger.hasHandlers():  # Behave better on reloads
AttributeError: Logger instance has no attribute 'hasHandlers'
```

**Comment by fcccbf8f8f1** [comment]
ditto.
```
Reloading plugin /Users/fcccbf8f8f1/Library/Application Support/Sublime Text 2/Packages/FindKeyConflicts/find_key_conflicts.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./find_key_conflicts.py", line 18, in <module>
    from lib.package_resources import *
  File "./lib/package_resources.py", line 293, in <module>
    reload(sys.modules["find_key_conflicts"])
  File "./find_key_conflicts.py", line 38, in <module>
    if not logger.hasHandlers():  # Behave better on reloads
AttributeError: Logger instance has no attribute 'hasHandlers'
```

**Comment by skuroda** [comment]
Sorry for taking so long on this quick fix. It should work with ST2 again.
